src/config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  resources :computers
  root to: 'announcements#index'

  resources :pools
  resources :transactions
  resources :banks
  resources :accounts
  resources :income_by_custommers
  resources :mining_histories
  resources :customers

  get '/city_report', to: 'report#report_city'
  get '/city_report2', to: 'report#report_city2'
  get "report" => "report#index", as: "report"
  get '/customer_pc_report', to: 'report#customer_pc'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/models/acc_type.rb
class AccType < ApplicationRecord
	has_many :accounts,  dependent: :destroy
end

src/app/models/account.rb
class Account < ApplicationRecord
  belongs_to :customer
  belongs_to :bank
  belongs_to :acc_type
  belongs_to :currency
  has_many :transactions, dependent: :destroy
end

src/app/models/announcement.rb
class Announcement < ApplicationRecord
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/bank.rb
class Bank < ApplicationRecord
	has_many :pools,  dependent: :destroy
	has_many :accounts,  dependent: :destroy
end

src/app/models/computer.rb
class Computer < ApplicationRecord
  belongs_to :customer
  has_many :mining_histories,  dependent: :destroy
end

src/app/models/currency.rb
class Currency < ApplicationRecord
	has_many :pools
	has_many :transactions
	has_many :accounts
end

src/app/models/customer.rb
class Customer < ApplicationRecord
	has_many :income_by_custommers,  dependent: :destroy
	has_many :computers,  dependent: :destroy
	has_many :accounts,  dependent: :destroy
end

src/app/models/income_by_custommer.rb
class IncomeByCustommer < ApplicationRecord
  belongs_to :customer
  belongs_to :pool
end

src/app/models/mining_history.rb
class MiningHistory < ApplicationRecord
  belongs_to :computer
  belongs_to :pool
end

src/app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :bank
  belongs_to :currency
  has_many :income_by_custommers,  dependent: :destroy
  has_many :mining_histories,  dependent: :destroy
end

src/app/models/trans_state.rb
class TransState < ApplicationRecord
	has_many :transactions,  dependent: :destroy
end

src/app/models/trans_type.rb
class TransType < ApplicationRecord
	has_many :transactions,  dependent: :destroy
end

src/app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :trans_state
  belongs_to :trans_type
  belongs_to :currency
end

src/app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, only: [:show, :edit, :update, :destroy]

  # GET /pools
  # GET /pools.json
  def index
    @pools = Pool.all.paginate(:page => params[:page], :per_page => 50)
  end

  # GET /pools/1
  # GET /pools/1.json
  def show
  end

  # GET /pools/new
  def new
    @pool = Pool.new
  end

  # GET /pools/1/edit
  def edit
  end

  # POST /pools
  # POST /pools.json
  def create
    @pool = Pool.new(pool_params)

    respond_to do |format|
      if @pool.save
        format.html { redirect_to @pool, notice: 'Pool was successfully created.' }
        format.json { render :show, status: :created, location: @pool }
      else
        format.html { render :new }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pools/1
  # PATCH/PUT /pools/1.json
  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to @pool, notice: 'Pool was successfully updated.' }
        format.json { render :show, status: :ok, location: @pool }
      else
        format.html { render :edit }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.json
  def destroy
    @pool.destroy
    respond_to do |format|
      format.html { redirect_to pools_url, notice: 'Pool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      @pool = Pool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pool_params
      params.require(:pool).permit(:name, :type, :income)
    end
end

src/app/helpers/accounts_helper.rb
module AccountsHelper
end

src/app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

end

src/app/helpers/banks_helper.rb
module BanksHelper
end

src/app/helpers/computers_helper.rb
module ComputersHelper
end

src/app/helpers/customers_helper.rb
module CustomersHelper
end

src/app/helpers/pools_helper.rb
module PoolsHelper
end

src/app/helpers/report_helper.rb
module ReportHelper
end

src/app/helpers/transactions_helper.rb
module TransactionsHelper
end

src/app/views/pools/_form.html.erb
<%= form_with(model: pool, local: true) do |form| %>
  <% if pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pool.errors.count, "error") %> prohibited this pool from being saved:</h2>

      <ul>
      <% pool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pool_name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :pool_type %>
  </div>

  <div class="field">
    <%= form.label :income %>
    <%= form.number_field :income, id: :pool_income %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/pools/edit.html.erb
<h1>Editing Pool</h1>

<%= render 'form', pool: @pool %>

<%= link_to 'Show', @pool %> |
<%= link_to 'Back', pools_path %>

src/app/views/pools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Income</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pools.each do |pool| %>
      <tr>
        <td><%= pool.name %></td>
        <td><%= pool.currency_id %></td>
        <td><%= pool.income %></td>
        <td><%= link_to 'Show', pool,class: "waves-effect waves-light btn" %></td>
        <td><%= link_to 'Edit', edit_pool_path(pool),class: "waves-effect waves-light btn" %></td>
        <td><%= link_to 'Destroy', pool, method: :delete, data: { confirm: 'Are you sure?' },class: "waves-effect waves-light btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<ul class="pagination">
  <%= will_paginate @pools %>
</ul>
<div class="fixed-action-btn horizontal direction-top direction-left">
  <%= link_to material_icon.add, new_pool_path, {:class=>"btn-floating btn-large waves-effect waves-light red" } %>
</div>

src/app/views/pools/new.html.erb
<h1>New Pool</h1>

<%= render 'form', pool: @pool %>

<%= link_to 'Back', pools_path %>

src/app/views/pools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pool.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @pool.type %>
</p>

<p>
  <strong>Income:</strong>
  <%= @pool.income %>
</p>

<%= link_to 'Edit', edit_pool_path(@pool) %> |
<%= link_to 'Back', pools_path %>