src/config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  resources :computers
  root to: 'announcements#index'

  resources :pools
  resources :transactions
  resources :banks
  resources :accounts
  resources :income_by_custommers
  resources :mining_histories
  resources :customers

  get '/city_report', to: 'report#report_city'
  get '/city_report2', to: 'report#report_city2'
  get "report" => "report#index", as: "report"
  get '/customer_pc_report', to: 'report#customer_pc'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/models/acc_type.rb
class AccType < ApplicationRecord
	has_many :accounts,  dependent: :destroy
end

src/app/models/account.rb
class Account < ApplicationRecord
  belongs_to :customer
  belongs_to :bank
  belongs_to :acc_type
  belongs_to :currency
  has_many :transactions, dependent: :destroy
end

src/app/models/announcement.rb
class Announcement < ApplicationRecord
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/bank.rb
class Bank < ApplicationRecord
	has_many :pools,  dependent: :destroy
	has_many :accounts,  dependent: :destroy
end

src/app/models/computer.rb
class Computer < ApplicationRecord
  belongs_to :customer
  has_many :mining_histories,  dependent: :destroy
end

src/app/models/currency.rb
class Currency < ApplicationRecord
	has_many :pools
	has_many :transactions
	has_many :accounts
end

src/app/models/customer.rb
class Customer < ApplicationRecord
	has_many :income_by_custommers,  dependent: :destroy
	has_many :computers,  dependent: :destroy
	has_many :accounts,  dependent: :destroy
end

src/app/models/income_by_custommer.rb
class IncomeByCustommer < ApplicationRecord
  belongs_to :customer
  belongs_to :pool
end

src/app/models/mining_history.rb
class MiningHistory < ApplicationRecord
  belongs_to :computer
  belongs_to :pool
end

src/app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :bank
  belongs_to :currency
  has_many :income_by_custommers,  dependent: :destroy
  has_many :mining_histories,  dependent: :destroy
end

src/app/models/trans_state.rb
class TransState < ApplicationRecord
	has_many :transactions,  dependent: :destroy
end

src/app/models/trans_type.rb
class TransType < ApplicationRecord
	has_many :transactions,  dependent: :destroy
end

src/app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :trans_state
  belongs_to :trans_type
  belongs_to :currency
end

src/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all.paginate(:page => params[:page], :per_page => 50)
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:number, :balance, :currency)
    end
end

src/app/helpers/accounts_helper.rb
module AccountsHelper
end

src/app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

end

src/app/helpers/banks_helper.rb
module BanksHelper
end

src/app/helpers/computers_helper.rb
module ComputersHelper
end

src/app/helpers/customers_helper.rb
module CustomersHelper
end

src/app/helpers/pools_helper.rb
module PoolsHelper
end

src/app/helpers/report_helper.rb
module ReportHelper
end

src/app/helpers/transactions_helper.rb
module TransactionsHelper
end

src/app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :account_number %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.number_field :balance, id: :account_balance %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency, id: :account_currency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

src/app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Balance</th>
      <th>Currency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.number %></td>
        <td><%= account.balance %></td>
        <td><%= account.currency_id %></td>
        <td><%= link_to 'Show', account,class: "waves-effect waves-light btn" %></td>
        <td><%= link_to 'Edit', edit_account_path(account),class: "waves-effect waves-light btn" %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' },class: "waves-effect waves-light btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<ul class="pagination">
  <%= will_paginate @accounts %>
</ul>
<div class="fixed-action-btn horizontal direction-top direction-left">
  <%= link_to material_icon.add, new_account_path, {:class=>"btn-floating btn-large waves-effect waves-light red" } %>
</div>

src/app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

src/app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @account.number %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @account.currency %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>