src/config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  resources :computers
  root to: 'announcements#index'

  resources :pools
  resources :transactions
  resources :banks
  resources :accounts
  resources :income_by_custommers
  resources :mining_histories
  resources :customers

  get '/city_report', to: 'report#report_city'
  get '/city_report2', to: 'report#report_city2'
  get "report" => "report#index", as: "report"
  get '/customer_pc_report', to: 'report#customer_pc'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/models/acc_type.rb
class AccType < ApplicationRecord
	has_many :accounts,  dependent: :destroy
end

src/app/models/account.rb
class Account < ApplicationRecord
  belongs_to :customer
  belongs_to :bank
  belongs_to :acc_type
  belongs_to :currency
  has_many :transactions, dependent: :destroy
end

src/app/models/announcement.rb
class Announcement < ApplicationRecord
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/bank.rb
class Bank < ApplicationRecord
	has_many :pools,  dependent: :destroy
	has_many :accounts,  dependent: :destroy
end

src/app/models/computer.rb
class Computer < ApplicationRecord
  belongs_to :customer
  has_many :mining_histories,  dependent: :destroy
end

src/app/models/currency.rb
class Currency < ApplicationRecord
	has_many :pools
	has_many :transactions
	has_many :accounts
end

src/app/models/customer.rb
class Customer < ApplicationRecord
	has_many :income_by_custommers,  dependent: :destroy
	has_many :computers,  dependent: :destroy
	has_many :accounts,  dependent: :destroy
end

src/app/models/income_by_custommer.rb
class IncomeByCustommer < ApplicationRecord
  belongs_to :customer
  belongs_to :pool
end

src/app/models/mining_history.rb
class MiningHistory < ApplicationRecord
  belongs_to :computer
  belongs_to :pool
end

src/app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :bank
  belongs_to :currency
  has_many :income_by_custommers,  dependent: :destroy
  has_many :mining_histories,  dependent: :destroy
end

src/app/models/trans_state.rb
class TransState < ApplicationRecord
	has_many :transactions,  dependent: :destroy
end

src/app/models/trans_type.rb
class TransType < ApplicationRecord
	has_many :transactions,  dependent: :destroy
end

src/app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :trans_state
  belongs_to :trans_type
  belongs_to :currency
end

src/app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all.paginate(:page => params[:page], :per_page => 50)
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:author, :text, :date)
    end
end

src/app/helpers/accounts_helper.rb
module AccountsHelper
end

src/app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

src/app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

end

src/app/helpers/banks_helper.rb
module BanksHelper
end

src/app/helpers/computers_helper.rb
module ComputersHelper
end

src/app/helpers/customers_helper.rb
module CustomersHelper
end

src/app/helpers/pools_helper.rb
module PoolsHelper
end

src/app/helpers/report_helper.rb
module ReportHelper
end

src/app/views/announcements/_form.html.erb
<%= form_with(model: announcement, local: true) do |form| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :announcement_author %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :announcement_text %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :announcement_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

src/app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Text</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.author %></td>
        <td><%= announcement.text %></td>
        <td><%= announcement.date %></td>
        <td><%= link_to 'Show', announcement,class: "waves-effect waves-light btn" %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement),class: "waves-effect waves-light btn" %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' },class: "waves-effect waves-light btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<ul class="pagination">
  <%= will_paginate @announcements %>
</ul>
<div class="fixed-action-btn horizontal direction-top direction-left">
  <%= link_to material_icon.add, new_announcement_path, {:class=>"btn-floating btn-large waves-effect waves-light red" } %>
</div>

src/app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Back', announcements_path %>

src/app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @announcement.author %>
</p>

<p>
  <strong>Text:</strong>
  <%= @announcement.text %>
</p>

<p>
  <strong>Date:</strong>
  <%= @announcement.date %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>