src/config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  resources :computers
  root to: 'announcements#index'

  resources :pools
  resources :transactions
  resources :banks
  resources :accounts
  resources :income_by_custommers
  resources :mining_histories
  resources :customers

  get '/city_report', to: 'report#report_city'
  get '/city_report2', to: 'report#report_city2'
  get "report" => "report#index", as: "report"
  get '/customer_pc_report', to: 'report#customer_pc'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/models/acc_type.rb
class AccType < ApplicationRecord
	has_many :accounts,  dependent: :destroy
end

src/app/models/account.rb
class Account < ApplicationRecord
  belongs_to :customer
  belongs_to :bank
  belongs_to :acc_type
  belongs_to :currency
  has_many :transactions, dependent: :destroy
end

src/app/models/announcement.rb
class Announcement < ApplicationRecord
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/bank.rb
class Bank < ApplicationRecord
	has_many :pools,  dependent: :destroy
	has_many :accounts,  dependent: :destroy
end

src/app/models/computer.rb
class Computer < ApplicationRecord
  belongs_to :customer
  has_many :mining_histories,  dependent: :destroy
end

src/app/models/currency.rb
class Currency < ApplicationRecord
	has_many :pools
	has_many :transactions
	has_many :accounts
end

src/app/models/customer.rb
class Customer < ApplicationRecord
	has_many :income_by_custommers,  dependent: :destroy
	has_many :computers,  dependent: :destroy
	has_many :accounts,  dependent: :destroy
end

src/app/models/income_by_custommer.rb
class IncomeByCustommer < ApplicationRecord
  belongs_to :customer
  belongs_to :pool
end

src/app/models/mining_history.rb
class MiningHistory < ApplicationRecord
  belongs_to :computer
  belongs_to :pool
end

src/app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :bank
  belongs_to :currency
  has_many :income_by_custommers,  dependent: :destroy
  has_many :mining_histories,  dependent: :destroy
end

src/app/models/trans_state.rb
class TransState < ApplicationRecord
	has_many :transactions,  dependent: :destroy
end

src/app/models/trans_type.rb
class TransType < ApplicationRecord
	has_many :transactions,  dependent: :destroy
end

src/app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :trans_state
  belongs_to :trans_type
  belongs_to :currency
end

src/app/controllers/report_controller.rb
class ReportController < ApplicationController
  require 'will_paginate/array'

  def index



  end

=begin
SELECT cu.first_name, cu.last_name, foo.pocet_pc FROM (
	SELECT com.customer_id as c_id, count(*) as pocet_pc FROM customers c
	JOIN computers com ON com.customer_id = c.id
	GROUP BY com.customer_id ) as foo
JOIN customers cu ON foo.c_id = cu.id;
=end
	 def customer_pc
     @vysledok = ActiveRecord::Base.connection.execute("
         SELECT c.first_name, c.last_name, foo.pocet_pc, foo.gpu_cores, foo.gpu_clock, foo.cpu_cores, foo.cpu_clock
FROM (
	SELECT com.customer_id as c_id, count(*) as pocet_pc, round(sum(com.gpu_cores),2) as gpu_cores,
		round(sum(com.gpu_clock)) as gpu_clock,
		round(sum(com.cpu_cores)) as cpu_cores,
		round(sum(com.cpu_clock)) as cpu_clock
	FROM customers c
	JOIN computers com ON com.customer_id = c.id
	GROUP BY com.customer_id) as foo
JOIN customers c ON c.id = foo.c_id
     ")
    @vysledok = @vysledok.to_a.paginate(:page => params[:page], :per_page => 12)
   end

	 def report_city

   end
#TODO opravit select
  def report_city2
    @parameter = params[:City].to_s
    @vysledok2 = ActiveRecord::Base.connection.execute("
SELECT b.bank_name, b.city, b.street, b.street_number, b.estabilished_date as date,
	coalesce(foo.pls, 0) as pools_count,
	coalesce(foo.ammount, 0) as pool_income
FROM banks b
FULL OUTER JOIN (
	SELECT bank_id as bnk, count(p.income) as pls, sum(p.income) as ammount FROM pools p
	GROUP BY p.bank_id ) as foo ON foo.bnk = b.id
WHERE b.city LIKE '"+@parameter+"%';
")
    @vysledok2 = @vysledok2.to_a.paginate(:page => params[:page], :per_page => 12)
  end
end

src/app/helpers/accounts_helper.rb
module AccountsHelper
end

src/app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

end

src/app/helpers/banks_helper.rb
module BanksHelper
end

src/app/helpers/computers_helper.rb
module ComputersHelper
end

src/app/helpers/customers_helper.rb
module CustomersHelper
end

src/app/helpers/pools_helper.rb
module PoolsHelper
end

src/app/helpers/report_helper.rb
module ReportHelper
end

src/app/views/report/customer_pc.html.erb
<h1>Customers PCs Report</h1>
<table>
  <thead>
  <tr>
    <th>Meno</th>
    <th>Priezvisko</th>
    <th>Pocet PC</th>
    <th>Suma frekvencie CPU</th>
    <th>Suma jadier CPU</th>
    <th>Suma frekvencie GPU</th>
    <th>Suma jadier GPU</th>
    <th colspan="7"></th>
  </tr>
  </thead>

  <tbody>
  <% @vysledok.each do |vysledok| %>
    <tr>
      <td><%= vysledok.fetch('first_name') %></td>
      <td><%= vysledok.fetch('last_name') %></td>
      <td><%= vysledok.fetch('pocet_pc') %></td>
      <td><%= vysledok.fetch('cpu_cores') %></td>
      <td><%= vysledok.fetch('cpu_clock') %></td>
      <td><%= vysledok.fetch('gpu_cores') %></td>
      <td><%= vysledok.fetch('gpu_clock') %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @vysledok %>

src/app/views/report/index.html.erb
<h1>Reports</h1>
<p> Vitajte na stranke reportov, na tejto stranke je mozny vyber z troch typov reportov. Uzivajte :)</p>

<br>

<%=link_to "Customer Report", customer_pc_report_path  %>
<%=link_to "City Report", city_report_path  %>

src/app/views/report/report_city.html.erb
<h3>Find customer by City</h3>
<%= form_tag("/city_report2", method: "get") do %>
  <%= text_field_tag(:City) %>
  <%= submit_tag("Hladaj") %>
<% end %>

<%= link_to material_icon.arrow_back, report_path %>

src/app/views/report/report_city2.html.erb
<h1>Bank Pool Report</h1>
<table>
  <thead>
  <tr>
    <th>Nazov Banky</th>
    <th>Mesto</th>
    <th>Ulica</th>
    <th>Popisne cislo</th>
    <th>Datum zalozenia</th>
    <th>Pocet poolov</th>
    <th>Celkovy príjem z poolov</th>
    <th colspan="7"></th>
  </tr>
  </thead>

  <tbody>
  <% @vysledok2.each do |vysledok| %>
    <tr>
      <td><%= vysledok.fetch('bank_name') %></td>
      <td><%= vysledok.fetch('city') %></td>
      <td><%= vysledok.fetch('street') %></td>
      <td><%= vysledok.fetch('street_number') %></td>
      <td><%= vysledok.fetch('date') %></td>
      <td><%= vysledok.fetch('pools_count') %></td>
      <td><%= vysledok.fetch('pool_income') %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @vysledok2 %>